### ISSUE TITLE
Add connection configuration

### ISSUE THREAD

**Issue by Faffnir** [houqp/terraform-provider-airflow#10]
I am currently working in a project which would like to configure a aws managed airflow instance with terraform. Unfortunately that's not possible through AWS API at all so I thought this solution would be neat.

One thing we desperately need would be the ability to configure connections.

I would also offer to implement it. Would this be in the interest of this project?

According to the airflow api documentation, it doesn't look to hard to implement? https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#tag/Connection

**Comment by houqp** [comment]
Yes, it should be pretty straight to implement this. Let me know if you need any help with it :)

**Comment by Faffnir** [comment]
I have sad news... I really looked forward on implementing this but as we are using the AWS managed airflow it is quite problematic authorization wise to reach the airflow api and it turned out that configuring the AWS Managed Airflow Ressource to use the AWS Secrets Backend turns out to be the easier solution.

Sorry for maybe raising hopes on implementing new features. Maybe we can use the airflow api in the future as aws managed airflow further develops. Thanks for the fast response!
