### ISSUE TITLE
example is broken

### ISSUE THREAD

**Issue by ivica-k** [houqp/terraform-provider-airflow#4]
Putting the following code in a `main.tf` and running `terraform init && terraform plan` results in errors

```
provider "airflow" {
  base_endpoint = "http://localhost:8080/"
  username      = "test"
  password      = "test"
}

resource "airflow_variable" "foo" {
  key   = "foo"
  value = "bar"
}

resource "airflow_variable" "hello" {
  key   = "hello"
  value = "world"
}
```

Errors
```
terraform plan

Error: Unsupported argument

  on main.tf line 2, in provider "airflow":
   2:   base_endpoint = "http://localhost:8080/"

An argument named "base_endpoint" is not expected here.


Error: Unsupported argument

  on main.tf line 3, in provider "airflow":
   3:   username      = "test"

An argument named "username" is not expected here.


Error: Unsupported argument

  on main.tf line 4, in provider "airflow":
   4:   password      = "test"

An argument named "password" is not expected here.
```

Removing all three arguments (username, password and base_endpoint) plans and applies without issues, but it creates a .json file locally.

**Comment by houqp** [comment]
The example was for unreleased version, I just released the latest master as v0.2.0, please give that a try :) Keep in mind that you need to run a fairly new unreleased version of Airflow since the new stable REST API with basic auth support is a very new feature .
